-- MySQL Dump
-- Generated by Railway Export

SET FOREIGN_KEY_CHECKS=0;


-- Table: favorites
DROP TABLE IF EXISTS `favorites`;
CREATE TABLE `favorites` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `song_id` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Data for table: favorites
INSERT INTO `favorites` (`id`, `user_id`, `song_id`, `created_at`) VALUES (2, 2, 0, '2026-05-12T05:55:20.000Z');
INSERT INTO `favorites` (`id`, `user_id`, `song_id`, `created_at`) VALUES (21, 2, 10, '2026-05-12T07:19:51.000Z');
INSERT INTO `favorites` (`id`, `user_id`, `song_id`, `created_at`) VALUES (22, 1, 10, '2026-05-12T09:25:27.000Z');
INSERT INTO `favorites` (`id`, `user_id`, `song_id`, `created_at`) VALUES (23, 3, 11, '2026-05-12T09:40:59.000Z');
INSERT INTO `favorites` (`id`, `user_id`, `song_id`, `created_at`) VALUES (24, 4, 8, '2026-05-12T09:47:05.000Z');
INSERT INTO `favorites` (`id`, `user_id`, `song_id`, `created_at`) VALUES (25, 4, 8, '2026-05-12T09:47:05.000Z');
INSERT INTO `favorites` (`id`, `user_id`, `song_id`, `created_at`) VALUES (26, 4, 8, '2026-05-12T09:47:05.000Z');
INSERT INTO `favorites` (`id`, `user_id`, `song_id`, `created_at`) VALUES (28, 2, 1, '2026-05-12T12:19:50.000Z');
INSERT INTO `favorites` (`id`, `user_id`, `song_id`, `created_at`) VALUES (29, 1, 26, '2026-05-12T12:45:49.000Z');


-- Table: songs
DROP TABLE IF EXISTS `songs`;
CREATE TABLE `songs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `artist` varchar(255) DEFAULT NULL,
  `src` text,
  `cover` text,
  `type` varchar(20) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `liked` tinyint(1) DEFAULT '0',
  `play_count` int DEFAULT '0',
  `category` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Data for table: songs
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (1, 'Mưa Tuyết', 'Lưu Đức Hoa', 'https://www.youtube.com/watch?v=3WNy7isGkyg&list=RD3WNy7isGkyg&start_radio=1', 'https://picsum.photos/300?0.9547979065117936', 'youtube', '2026-05-12T05:54:58.000Z', 0, 8, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (2, 'Hạt Mưa Vương Vấn', 'Kiều Chi', 'https://youtu.be/UwDKu7VYtTw?si=zsQMhTorAOw-8BLv', 'https://picsum.photos/300?0.5152473085074627', 'youtube', '2026-05-12T05:54:58.000Z', 0, 2, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (3, 'Anh Không Theo Đuổi Em Nữa', 'Bùi Công Nam', 'https://www.youtube.com/watch?v=A-Ab7_R_P7k&list=RDA-Ab7_R_P7k&start_radio=1', 'https://picsum.photos/300?0.5152473085074628', 'youtube', '2026-05-12T05:54:58.000Z', 0, 3, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (4, 'Thắc Mắc', 'Thịnh Suy', 'https://www.youtube.com/watch?v=YTQ-n0SgdiY&list=RDYTQ-n0SgdiY&start_radio=1', 'https://picsum.photos/300?0.6265754068950204', NULL, '2026-05-12T05:54:58.000Z', 0, 7, 'V-Pop');
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (7, 'Người im lặng gặp người hay nói', 'HIEUTHUHAI', 'https://www.youtube.com/watch?v=8sVtL0o-v7U&list=RD8sVtL0o-v7U&start_radio=1', 'https://picsum.photos/300?sig=0.06779023932147155', 'youtube', '2026-05-11T08:51:17.000Z', 0, 12, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (8, 'Mùa mưa ấy', 'VŨ', 'https://www.youtube.com/watch?v=QQzt-veR3fY&list=RDQQzt-veR3fY&start_radio=1', 'https://picsum.photos/300?sig=0.7730273679795903', 'youtube', '2026-05-11T08:51:56.000Z', 1, 20, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (13, 'Thuỷ Chung', 'Thương Võ', 'https://www.youtube.com/watch?v=w68MGL20Mf0&list=RDw68MGL20Mf0&start_radio=1', 'https://picsum.photos/seed/959/300/300', 'youtube', '2026-05-12T09:47:21.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (14, 'Nguyệt Hồng Phai', 'Huy TK x NH4T x Pha', 'https://www.youtube.com/watch?v=kMndAaasXz4&list=RDkMndAaasXz4&start_radio=1', 'https://picsum.photos/seed/227/300/300', 'youtube', '2026-05-12T09:49:33.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (15, 'Khóc', 'Đông Nhi', 'https://www.youtube.com/watch?v=LJ7CzmQ05bs&list=RDLJ7CzmQ05bs&start_radio=1', 'https://picsum.photos/seed/324/300/300', 'youtube', '2026-05-12T09:50:49.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (16, 'Sơn Thuỷ Trùng Mây', 'Jena ft. Anh Rồng || Prod. SinKra', 'https://www.youtube.com/watch?v=g19WtuuJvyQ&list=RDg19WtuuJvyQ&start_radio=1', 'https://picsum.photos/seed/488/300/300', 'youtube', '2026-05-12T09:52:15.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (17, 'Hứa Thật Nhiều Thất Hứa Thật Nhiều', 'Ưng Hoàng Phúc', 'https://www.youtube.com/watch?v=waJ2QujRGZE&list=RDwaJ2QujRGZE&start_radio=1', 'https://picsum.photos/seed/202/300/300', 'youtube', '2026-05-12T09:53:24.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (18, 'Canh Bạc Làm Dâu 2', 'Nghệ sĩ ẩn danh', 'https://www.youtube.com/watch?v=ueSOtFrKwHk&list=RDueSOtFrKwHk&start_radio=1', 'https://picsum.photos/seed/944/300/300', 'youtube', '2026-05-12T09:55:13.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (19, 'Câu Hứa Chưa Vẹn Tròn', 'PHÁT HUY T4 x HOÀNG GREEN', 'https://www.youtube.com/watch?v=uI4hZ5CQJ_8&list=RDuI4hZ5CQJ_8&start_radio=1', 'https://picsum.photos/seed/665/300/300', 'youtube', '2026-05-12T12:12:02.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (20, 'Như Bến Đợi Đò', 'Khánh Ân ft. Hana Cẩm Tiên', 'https://www.youtube.com/watch?v=riAUtsj-PWE&list=RDriAUtsj-PWE&start_radio=1', 'https://picsum.photos/seed/612/300/300', 'youtube', '2026-05-12T12:13:20.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (21, 'Hạt Mưa Vương Vấn', 'Nghệ sĩ ẩn danh', 'https://www.youtube.com/watch?v=YGeExm0vJBA&list=RDYGeExm0vJBA&start_radio=1', 'https://picsum.photos/seed/748/300/300', 'youtube', '2026-05-12T12:20:18.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (22, 'Lỡ Một Lời Thương', 'Vy Oanh', 'https://www.youtube.com/watch?v=gOYqh3gX-WA&list=RDgOYqh3gX-WA&start_radio=1', 'https://picsum.photos/seed/864/300/300', 'youtube', '2026-05-12T12:21:31.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (23, 'Quay Lưng', 'TLong', 'https://www.youtube.com/watch?v=Hlb3mtWdlHc&list=RDHlb3mtWdlHc&start_radio=1', 'https://picsum.photos/seed/917/300/300', 'youtube', '2026-05-12T12:24:01.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (24, 'Tòng Phu', 'Keyo x Đại Mèo', 'https://www.youtube.com/watch?v=VV0Xm34-NSQ&list=RDVV0Xm34-NSQ&start_radio=1', 'https://picsum.photos/seed/28/300/300', 'youtube', '2026-05-12T12:26:31.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (25, 'Người Ta', 'Đoàn Khánh Linh x RIN Muzik', 'https://www.youtube.com/watch?v=vScdXKP1snM&list=RDvScdXKP1snM&start_radio=1', 'https://picsum.photos/seed/118/300/300', 'youtube', '2026-05-12T12:27:30.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (26, 'Chỉ Là Lừa Dối', 'Hoàng Ly', 'https://www.youtube.com/watch?v=bZd_WkoCfnI&list=RDbZd_WkoCfnI&start_radio=1', 'https://picsum.photos/seed/899/300/300', 'youtube', '2026-05-12T12:31:41.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (27, 'Kiếp Má Hồng', 'TLong', 'https://www.youtube.com/watch?v=NID-LUWJJjU&list=RDNID-LUWJJjU&start_radio=1', 'https://picsum.photos/seed/22/300/300', 'youtube', '2026-05-12T12:33:06.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (28, 'Hẹn Hò Nhưng Không Yêu', 'Wendy Thảo', 'https://www.youtube.com/watch?v=yWb4sgcgLvQ&list=RDyWb4sgcgLvQ&start_radio=1', 'https://picsum.photos/seed/277/300/300', 'youtube', '2026-05-12T12:33:57.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (29, 'Chẳng Thể Cảm Hoá', 'Lương Quý Tuấn x An Clock', 'https://www.youtube.com/watch?v=QiyNixKJSdc&list=RDQiyNixKJSdc&start_radio=1', 'https://picsum.photos/seed/380/300/300', 'youtube', '2026-05-12T12:35:45.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (30, 'Trưởng Thành', 'DimZ x Đại Mèo', 'https://www.youtube.com/watch?v=QeLbOEw0DUs&list=RDQeLbOEw0DUs&start_radio=1', 'https://picsum.photos/seed/805/300/300', 'youtube', '2026-05-12T12:40:39.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (31, 'Xa Vắng [Lofi Ver.]', 'Thành Đạt Cover x Trạm Xưa', 'https://www.youtube.com/watch?v=dwGyCjJS4SE&list=RDdwGyCjJS4SE&start_radio=1', 'https://picsum.photos/seed/452/300/300', 'youtube', '2026-05-12T12:42:30.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (32, 'Nhìn Em Vu Quy', 'Huỳnh Văn', 'https://www.youtube.com/watch?v=1X5yS16HhXA&list=RD1X5yS16HhXA&start_radio=1', 'https://picsum.photos/seed/419/300/300', 'youtube', '2026-05-12T12:44:29.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (33, 'Đến Lúc Phải Đi Rồi', 'HUYỀN ANH', 'https://www.youtube.com/watch?v=DwrE3MkLtPM&list=RDDwrE3MkLtPM&start_radio=1', 'https://picsum.photos/seed/964/300/300', 'youtube', '2026-05-12T12:45:46.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (34, 'Cánh Hoa Héo Tàn', 'Mochiii', 'https://www.youtube.com/watch?v=YizrmzMvr7Q&list=LL&index=7', 'https://picsum.photos/seed/385/300/300', 'youtube', '2026-05-12T12:46:57.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (35, 'Góc Nhỏ Trong Tim', 'Khởi My', 'https://www.youtube.com/watch?v=aWuDIgGzkIQ&list=RDaWuDIgGzkIQ&start_radio=1', 'https://picsum.photos/seed/570/300/300', 'youtube', '2026-05-12T12:48:33.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (36, 'Mưa Rơi Vào Phòng', 'Khởi My', 'https://www.youtube.com/watch?v=1rQe6KG-y_c&list=RD1rQe6KG-y_c&start_radio=1', 'https://picsum.photos/seed/141/300/300', 'youtube', '2026-05-12T12:49:31.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (37, 'Người Lạ Thoáng Qua', 'Khởi My', 'https://www.youtube.com/watch?v=L1ifnr6Il98&list=RDL1ifnr6Il98&start_radio=1', 'https://picsum.photos/seed/801/300/300', 'youtube', '2026-05-12T12:50:52.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (38, 'Lo Người Ướt Áo', 'Nguyễn Thạc Bảo Ngọc', 'https://www.youtube.com/watch?v=usBJRm0DNl0&list=RDusBJRm0DNl0&start_radio=1', 'https://picsum.photos/seed/494/300/300', 'youtube', '2026-05-12T12:53:35.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (39, 'Khóc Nơi Ta Cười', 'ĐINH TÙNG HUY', 'https://www.youtube.com/watch?v=QLITs08WrXs&list=RDQLITs08WrXs&start_radio=1', 'https://picsum.photos/seed/187/300/300', 'youtube', '2026-05-12T12:55:11.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (40, 'Nơi Tình Yêu Kết Thúc', 'Bùi Anh Tuấn', 'https://www.youtube.com/watch?v=4S0jwsH7WYw&list=RD4S0jwsH7WYw&start_radio=1', 'https://picsum.photos/seed/12/300/300', 'youtube', '2026-05-12T12:57:10.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (41, 'Nhường Lại Nổi Đau', 'Ngân Ngân', 'https://www.youtube.com/watch?v=0HO3_7fI0zk&list=RD0HO3_7fI0zk&start_radio=1', 'https://picsum.photos/seed/317/300/300', 'youtube', '2026-05-12T12:58:11.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (42, 'Một Giấc Phiêu Bồng', 'Chu Thúy Quỳnh', 'https://www.youtube.com/watch?v=xYQyZJZ3mMA&list=RDxYQyZJZ3mMA&start_radio=1', 'https://picsum.photos/seed/547/300/300', 'youtube', '2026-05-12T12:59:04.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (43, '7 Lần Vấp Ngã 8 Lần Đứng Lên', 'MiiNa x RIN9', 'https://www.youtube.com/watch?v=XphkSOkSX04&list=RDXphkSOkSX04&start_radio=1', 'https://picsum.photos/seed/192/300/300', 'youtube', '2026-05-12T13:00:27.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (44, 'Thuận Theo Ý Trời', 'Bùi Anh Tuấn', 'https://www.youtube.com/watch?v=JydxSlCND-k&list=RDJydxSlCND-k&start_radio=1', 'https://picsum.photos/seed/935/300/300', 'youtube', '2026-05-12T13:01:32.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (45, 'Ngôi Nhà Hạnh Phúc', 'NHẬT PHÁT', 'https://www.youtube.com/watch?v=vKuHQRTS20U&list=RDvKuHQRTS20U&start_radio=1', 'https://picsum.photos/seed/473/300/300', 'youtube', '2026-05-12T13:04:37.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (46, 'Sâu Sắc', 'Thịnh Qino', 'https://www.youtube.com/watch?v=f8aGVWG2xEk&list=RDf8aGVWG2xEk&start_radio=1', 'https://picsum.photos/seed/405/300/300', 'youtube', '2026-05-12T13:05:40.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (47, 'Nắng Lung Linh', 'NGUYỄN THƯƠNG', 'https://www.youtube.com/watch?v=BsNm0Zv6hnE&list=RDBsNm0Zv6hnE&start_radio=1', 'https://picsum.photos/seed/235/300/300', 'youtube', '2026-05-12T13:06:43.000Z', 0, 0, NULL);
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (48, 'Đừng Như Thói Quen', 'JayKii FT Sara Lưu', 'https://www.youtube.com/watch?v=8BVAuWusBBA&list=RD8BVAuWusBBA&start_radio=1', 'https://picsum.photos/seed/508/300/300', NULL, '2026-05-12T13:07:36.000Z', 0, 0, 'Lo-fi');
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (49, 'Đớn Đau Vô Cùng', 'DATKAA x PROD. QT', 'https://www.youtube.com/watch?v=s76BtB81Oms&list=RDs76BtB81Oms&start_radio=1', 'https://picsum.photos/seed/172/300/300', NULL, '2026-05-12T13:11:24.000Z', 0, 0, 'V-Pop');
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (50, 'Mở Lòng Vì Ai', 'Inso Cover s', 'https://www.youtube.com/watch?v=TS04y03CEsI&list=RDTS04y03CEsI&start_radio=1', 'https://picsum.photos/seed/35/300/300', NULL, '2026-05-13T01:44:51.000Z', 0, 0, 'Remix');
INSERT INTO `songs` (`id`, `title`, `artist`, `src`, `cover`, `type`, `created_at`, `liked`, `play_count`, `category`) VALUES (51, 'Những Chuyến Bay', 'Vũ', 'https://www.youtube.com/watch?v=BFv_khsMfKM&list=RDBFv_khsMfKM&start_radio=1', 'https://picsum.photos/seed/196/300/300', NULL, '2026-05-13T02:13:49.000Z', 0, 0, 'V-Pop');


-- Table: users
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(100) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `role` enum('admin','user') DEFAULT 'user',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Data for table: users
INSERT INTO `users` (`id`, `username`, `password`, `role`, `created_at`) VALUES (1, 'admin', '123456', 'admin', '2026-05-12T05:54:58.000Z');
INSERT INTO `users` (`id`, `username`, `password`, `role`, `created_at`) VALUES (2, 'nam', '123', 'user', '2026-05-12T05:54:58.000Z');
INSERT INTO `users` (`id`, `username`, `password`, `role`, `created_at`) VALUES (3, 'tuan', '123', 'user', '2026-05-12T09:37:59.000Z');
INSERT INTO `users` (`id`, `username`, `password`, `role`, `created_at`) VALUES (4, 'hoang', '123', 'user', '2026-05-12T09:44:41.000Z');
INSERT INTO `users` (`id`, `username`, `password`, `role`, `created_at`) VALUES (5, 'nhut', '123', 'user', '2026-05-12T10:01:10.000Z');

SET FOREIGN_KEY_CHECKS=1;
